---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    author: vidya
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 8080
  selector:
    author: vidya
    type: ci-cd

...
