---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    type: proxy
spec:
  containers:
    - name: mynginx
      image: nginx
  tolerations:
    - key: slave2
      value: vidya2
      effect: NoSchedule
      operator: Equal
...