---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    author: vidya
spec:
  containers:
    - name: my-redis
      image: redis
      volumeMounts:
        - name: my-volume
          mountPath: /data/redis
  volumes:
    - name: my-volume
      emptyDir: {}

    
...
